### ISSUE TITLE
Patcher producing identical output to source under Wine

### ISSUE THREAD

**Issue by robbie01** [DerekPascarella/UniversalDreamcastPatcher#1]
I am attempting to patch Sakura Wars Columns 2 under Wine. While the patcher is showing messages that appear to be doing something (verifying integrity, patching individual files, etc.), the resultant files in the directory created by the patcher are identical to the source down to the byte in all of the GDI, track01.bin, track02.raw, and track03.bin, effectively making the Universal Dreamcast Patcher a CPU-intensive copy operation. I verified this with the coreutils `cmp` utility.

**Comment by DerekPascarella** [comment]
Thank you for your feedback.

I'm not surprised you're experiencing issues, as the patcher leverages numerous "helper" utilities under the hood throughout the process of patching and building the new GDI.  I suspect that one or more of said helper utilities is failing under WINE.

Unfortunately, I've never tested UDP's operation in WINE, and it's not called out as specifically supported in the [README](https://github.com/DerekPascarella/UniversalDreamcastPatcher/blob/main/README.md).  That being said, I _would_ like to write a version that runs natively on Linux one day (see the [Roadmap](https://github.com/DerekPascarella/UniversalDreamcastPatcher#roadmap) section).

I'd like to add that I'm a Linux enthusiast myself, however such an overwhelming bulk of the Dreamcast hacking/reverse-engineering ecosystem relies on Windows.  As a result, this is the OS targeted for Universal Dreamcast Patcher.  I feel bad that you're not able to use it without spinning up a VM or using another machine, but I'm afraid I can't do much about that presently.

If you're still interested in playing "Sakura Wars: Columns 2", feel free to contact me directly by using one of the platforms listed here: https://dreamcastforever.com/?page=contact_information

**Comment by sl1pkn07** [comment]
hi

sadly, without linux or mac support, the universal word is not all the universal word means

is not possible send patches to wine devs for at least, make these incompatible methods/programs, wine compatible without use a VM/real windows machine?

greetings

**Comment by Sanaki** [comment]
As of Wine 9.2 it appears to function as expected, though it'll produce the patched file directory alongside the executable, not the disc image.

**Comment by DerekPascarella** [comment]
Thanks for the comment.

However, can you clarify what you mean? The patched GDI folder is created within the application's working directory (as is expected behavior), but is empty?

**Comment by Sanaki** [comment]
No, it contained the patched game. Most tools would produce the patch directory alongside the target image rather than in the program directory. That said, this is definitely a Linux-oriented expectation, since we're used to throwing executables in the PATH and not needing to know where they reside.
