### ISSUE TITLE
CUE input results in horribly broken GDI output

### ISSUE THREAD

**Issue by rhester72** [DerekPascarella/UniversalDreamcastPatcher#2]
Try patching the redump release "Hydro Thunder (USA) (Rev 1).zip".  The resulting disc.gdi will be completely out of sequence and random output tracks (e.g. track37.bin and track037.bin with different content!) will be produced.  This is reproducible with every available VGA patch from here:

https://consolemods.org/wiki/Dreamcast:List_of_VGA_Games_and_Patches

and is never reproducible with GDI _input_, only CUE.

I reproduced this in both 1.4 and 1.5 releases but did not go back further.

**Comment by DerekPascarella** [comment]
Thank you for the report. I will investigate and hopefully fix tomorrow.

In the mean time, you can use the TOSEC GDI dumps as source without issue. They'll still be compatible with any emulator or ODE (and my patcher always outputs to GDI anyway, it cannot produce Redump-style disc images yet).

**Comment by DerekPascarella** [comment]
Fixed with v1.6 release.
